In [1]:
import pandas as pd

In [2]:
import json

In [3]:
with open("C:\\Users\\Bhavya Sree\\Downloads\\t20_wc_match_results.json") as f:
    data = json.load(f)
print(data)

[{'matchSummary': [{'team1': 'Namibia', 'team2': 'Sri Lanka', 'winner': 'Namibia', 'margin': '55 runs', 'ground': 'Geelong', 'matchDate': 'Oct 16, 2022', 'scorecard': 'T20I # 1823'}, {'team1': 'Netherlands', 'team2': 'U.A.E.', 'winner': 'Netherlands', 'margin': '3 wickets', 'ground': 'Geelong', 'matchDate': 'Oct 16, 2022', 'scorecard': 'T20I # 1825'}, {'team1': 'Scotland', 'team2': 'West Indies', 'winner': 'Scotland', 'margin': '42 runs', 'ground': 'Hobart', 'matchDate': 'Oct 17, 2022', 'scorecard': 'T20I # 1826'}, {'team1': 'Ireland', 'team2': 'Zimbabwe', 'winner': 'Zimbabwe', 'margin': '31 runs', 'ground': 'Hobart', 'matchDate': 'Oct 17, 2022', 'scorecard': 'T20I # 1828'}, {'team1': 'Namibia', 'team2': 'Netherlands', 'winner': 'Netherlands', 'margin': '5 wickets', 'ground': 'Geelong', 'matchDate': 'Oct 18, 2022', 'scorecard': 'T20I # 1830'}, {'team1': 'Sri Lanka', 'team2': 'U.A.E.', 'winner': 'Sri Lanka', 'margin': '79 runs', 'ground': 'Geelong', 'matchDate': 'Oct 18, 2022', 'scorecard': 'T20I # 1832'}, {'team1': 'Ireland', 'team2': 'Scotland', 'winner': 'Ireland', 'margin': '6 wickets', 'ground': 'Hobart', 'matchDate': 'Oct 19, 2022', 'scorecard': 'T20I # 1833'}, {'team1': 'West Indies', 'team2': 'Zimbabwe', 'winner': 'West Indies', 'margin': '31 runs', 'ground': 'Hobart', 'matchDate': 'Oct 19, 2022', 'scorecard': 'T20I # 1834'}, {'team1': 'Netherlands', 'team2': 'Sri Lanka', 'winner': 'Sri Lanka', 'margin': '16 runs', 'ground': 'Geelong', 'matchDate': 'Oct 20, 2022', 'scorecard': 'T20I # 1835'}, {'team1': 'Namibia', 'team2': 'U.A.E.', 'winner': 'U.A.E.', 'margin': '7 runs', 'ground': 'Geelong', 'matchDate': 'Oct 20, 2022', 'scorecard': 'T20I # 1836'}, {'team1': 'Ireland', 'team2': 'West Indies', 'winner': 'Ireland', 'margin': '9 wickets', 'ground': 'Hobart', 'matchDate': 'Oct 21, 2022', 'scorecard': 'T20I # 1837'}, {'team1': 'Scotland', 'team2': 'Zimbabwe', 'winner': 'Zimbabwe', 'margin': '5 wickets', 'ground': 'Hobart', 'matchDate': 'Oct 21, 2022', 'scorecard': 'T20I # 1838'}, {'team1': 'Australia', 'team2': 'New Zealand', 'winner': 'New Zealand', 'margin': '89 runs', 'ground': 'Sydney', 'matchDate': 'Oct 22, 2022', 'scorecard': 'T20I # 1839'}, {'team1': 'Afghanistan', 'team2': 'England', 'winner': 'England', 'margin': '5 wickets', 'ground': 'Perth', 'matchDate': 'Oct 22, 2022', 'scorecard': 'T20I # 1840'}, {'team1': 'Ireland', 'team2': 'Sri Lanka', 'winner': 'Sri Lanka', 'margin': '9 wickets', 'ground': 'Hobart', 'matchDate': 'Oct 23, 2022', 'scorecard': 'T20I # 1841'}, {'team1': 'India', 'team2': 'Pakistan', 'winner': 'India', 'margin': '4 wickets', 'ground': 'Melbourne', 'matchDate': 'Oct 23, 2022', 'scorecard': 'T20I # 1842'}, {'team1': 'Bangladesh', 'team2': 'Netherlands', 'winner': 'Bangladesh', 'margin': '9 runs', 'ground': 'Hobart', 'matchDate': 'Oct 24, 2022', 'scorecard': 'T20I # 1843'}, {'team1': 'South Africa', 'team2': 'Zimbabwe', 'winner': 'no result', 'margin': '', 'ground': 'Hobart', 'matchDate': 'Oct 24, 2022', 'scorecard': 'T20I # 1844'}, {'team1': 'Australia', 'team2': 'Sri Lanka', 'winner': 'Australia', 'margin': '7 wickets', 'ground': 'Perth', 'matchDate': 'Oct 25, 2022', 'scorecard': 'T20I # 1845'}, {'team1': 'England', 'team2': 'Ireland', 'winner': 'Ireland', 'margin': '5 runs', 'ground': 'Melbourne', 'matchDate': 'Oct 26, 2022', 'scorecard': 'T20I # 1846'}, {'team1': 'Afghanistan', 'team2': 'New Zealand', 'winner': 'abandoned', 'margin': '', 'ground': 'Melbourne', 'matchDate': 'Oct 26, 2022', 'scorecard': 'T20I # 1846a'}, {'team1': 'Bangladesh', 'team2': 'South Africa', 'winner': 'South Africa', 'margin': '104 runs', 'ground': 'Sydney', 'matchDate': 'Oct 27, 2022', 'scorecard': 'T20I # 1847'}, {'team1': 'India', 'team2': 'Netherlands', 'winner': 'India', 'margin': '56 runs', 'ground': 'Sydney', 'matchDate': 'Oct 27, 2022', 'scorecard': 'T20I # 1848'}, {'team1': 'Pakistan', 'team2': 'Zimbabwe', 'winner': 'Zimbabwe', 'margin': '1 run', 'ground': 'Perth', 'matchDate': 'Oct 27, 2022', 'scorecard': 'T20I # 1849'}, {'team1': 'Afghanistan', 'team2': 'Ireland', 'winner': 'abandoned', 'margin': '', 'ground': 'Melbourne', 'matchDate': 'Oct 28, 2022', 'scorecard': 'T20I # 1849a'}, {'team1': 'Australia', 'team2': 'England', 'winner': 'abandoned', 'margin': '', 'ground': 'Melbourne', 'matchDate': 'Oct 28, 2022', 'scorecard': 'T20I # 1849b'}, {'team1': 'New Zealand', 'team2': 'Sri Lanka', 'winner': 'New Zealand', 'margin': '65 runs', 'ground': 'Sydney', 'matchDate': 'Oct 29, 2022', 'scorecard': 'T20I # 1850'}, {'team1': 'Bangladesh', 'team2': 'Zimbabwe', 'winner': 'Bangladesh', 'margin': '3 runs', 'ground': 'Brisbane', 'matchDate': 'Oct 30, 2022', 'scorecard': 'T20I # 1851'}, {'team1': 'Netherlands', 'team2': 'Pakistan', 'winner': 'Pakistan', 'margin': '6 wickets', 'ground': 'Perth', 'matchDate': 'Oct 30, 2022', 'scorecard': 'T20I # 1852'}, {'team1': 'India', 'team2': 'South Africa', 'winner': 'South Africa', 'margin': '5 wickets', 'ground': 'Perth', 'matchDate': 'Oct 30, 2022', 'scorecard': 'T20I # 1853'}, {'team1': 'Australia', 'team2': 'Ireland', 'winner': 'Australia', 'margin': '42 runs', 'ground': 'Brisbane', 'matchDate': 'Oct 31, 2022', 'scorecard': 'T20I # 1855'}, {'team1': 'Afghanistan', 'team2': 'Sri Lanka', 'winner': 'Sri Lanka', 'margin': '6 wickets', 'ground': 'Brisbane', 'matchDate': 'Nov 1, 2022', 'scorecard': 'T20I # 1856'}, {'team1': 'England', 'team2': 'New Zealand', 'winner': 'England', 'margin': '20 runs', 'ground': 'Brisbane', 'matchDate': 'Nov 1, 2022', 'scorecard': 'T20I # 1858'}, {'team1': 'Netherlands', 'team2': 'Zimbabwe', 'winner': 'Netherlands', 'margin': '5 wickets', 'ground': 'Adelaide', 'matchDate': 'Nov 2, 2022', 'scorecard': 'T20I # 1859'}, {'team1': 'Bangladesh', 'team2': 'India', 'winner': 'India', 'margin': '5 runs', 'ground': 'Adelaide', 'matchDate': 'Nov 2, 2022', 'scorecard': 'T20I # 1860'}, {'team1': 'Pakistan', 'team2': 'South Africa', 'winner': 'Pakistan', 'margin': '33 runs', 'ground': 'Sydney', 'matchDate': 'Nov 3, 2022', 'scorecard': 'T20I # 1861'}, {'team1': 'Ireland', 'team2': 'New Zealand', 'winner': 'New Zealand', 'margin': '35 runs', 'ground': 'Adelaide', 'matchDate': 'Nov 4, 2022', 'scorecard': 'T20I # 1862'}, {'team1': 'Australia', 'team2': 'Afghanistan', 'winner': 'Australia', 'margin': '4 runs', 'ground': 'Adelaide', 'matchDate': 'Nov 4, 2022', 'scorecard': 'T20I # 1864'}, {'team1': 'England', 'team2': 'Sri Lanka', 'winner': 'England', 'margin': '4 wickets', 'ground': 'Sydney', 'matchDate': 'Nov 5, 2022', 'scorecard': 'T20I # 1867'}, {'team1': 'Netherlands', 'team2': 'South Africa', 'winner': 'Netherlands', 'margin': '13 runs', 'ground': 'Adelaide', 'matchDate': 'Nov 6, 2022', 'scorecard': 'T20I # 1871'}, {'team1': 'Bangladesh', 'team2': 'Pakistan', 'winner': 'Pakistan', 'margin': '5 wickets', 'ground': 'Adelaide', 'matchDate': 'Nov 6, 2022', 'scorecard': 'T20I # 1872'}, {'team1': 'India', 'team2': 'Zimbabwe', 'winner': 'India', 'margin': '71 runs', 'ground': 'Melbourne', 'matchDate': 'Nov 6, 2022', 'scorecard': 'T20I # 1873'}, {'team1': 'New Zealand', 'team2': 'Pakistan', 'winner': 'Pakistan', 'margin': '7 wickets', 'ground': 'Sydney', 'matchDate': 'Nov 9, 2022', 'scorecard': 'T20I # 1877'}, {'team1': 'England', 'team2': 'India', 'winner': 'England', 'margin': '10 wickets', 'ground': 'Adelaide', 'matchDate': 'Nov 10, 2022', 'scorecard': 'T20I # 1878'}, {'team1': 'England', 'team2': 'Pakistan', 'winner': 'England', 'margin': '5 wickets', 'ground': 'Melbourne', 'matchDate': 'Nov 13, 2022', 'scorecard': 'T20I # 1879'}]}]

In [4]:
data

[{'matchSummary': [{'team1': 'Namibia',
    'team2': 'Sri Lanka',
    'winner': 'Namibia',
    'margin': '55 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 16, 2022',
    'scorecard': 'T20I # 1823'},
   {'team1': 'Netherlands',
    'team2': 'U.A.E.',
    'winner': 'Netherlands',
    'margin': '3 wickets',
    'ground': 'Geelong',
    'matchDate': 'Oct 16, 2022',
    'scorecard': 'T20I # 1825'},
   {'team1': 'Scotland',
    'team2': 'West Indies',
    'winner': 'Scotland',
    'margin': '42 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 17, 2022',
    'scorecard': 'T20I # 1826'},
   {'team1': 'Ireland',
    'team2': 'Zimbabwe',
    'winner': 'Zimbabwe',
    'margin': '31 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 17, 2022',
    'scorecard': 'T20I # 1828'},
   {'team1': 'Namibia',
    'team2': 'Netherlands',
    'winner': 'Netherlands',
    'margin': '5 wickets',
    'ground': 'Geelong',
    'matchDate': 'Oct 18, 2022',
    'scorecard': 'T20I # 1830'},
   {'team1': 'Sri Lanka',
    'team2': 'U.A.E.',
    'winner': 'Sri Lanka',
    'margin': '79 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 18, 2022',
    'scorecard': 'T20I # 1832'},
   {'team1': 'Ireland',
    'team2': 'Scotland',
    'winner': 'Ireland',
    'margin': '6 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 19, 2022',
    'scorecard': 'T20I # 1833'},
   {'team1': 'West Indies',
    'team2': 'Zimbabwe',
    'winner': 'West Indies',
    'margin': '31 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 19, 2022',
    'scorecard': 'T20I # 1834'},
   {'team1': 'Netherlands',
    'team2': 'Sri Lanka',
    'winner': 'Sri Lanka',
    'margin': '16 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 20, 2022',
    'scorecard': 'T20I # 1835'},
   {'team1': 'Namibia',
    'team2': 'U.A.E.',
    'winner': 'U.A.E.',
    'margin': '7 runs',
    'ground': 'Geelong',
    'matchDate': 'Oct 20, 2022',
    'scorecard': 'T20I # 1836'},
   {'team1': 'Ireland',
    'team2': 'West Indies',
    'winner': 'Ireland',
    'margin': '9 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 21, 2022',
    'scorecard': 'T20I # 1837'},
   {'team1': 'Scotland',
    'team2': 'Zimbabwe',
    'winner': 'Zimbabwe',
    'margin': '5 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 21, 2022',
    'scorecard': 'T20I # 1838'},
   {'team1': 'Australia',
    'team2': 'New Zealand',
    'winner': 'New Zealand',
    'margin': '89 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 22, 2022',
    'scorecard': 'T20I # 1839'},
   {'team1': 'Afghanistan',
    'team2': 'England',
    'winner': 'England',
    'margin': '5 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 22, 2022',
    'scorecard': 'T20I # 1840'},
   {'team1': 'Ireland',
    'team2': 'Sri Lanka',
    'winner': 'Sri Lanka',
    'margin': '9 wickets',
    'ground': 'Hobart',
    'matchDate': 'Oct 23, 2022',
    'scorecard': 'T20I # 1841'},
   {'team1': 'India',
    'team2': 'Pakistan',
    'winner': 'India',
    'margin': '4 wickets',
    'ground': 'Melbourne',
    'matchDate': 'Oct 23, 2022',
    'scorecard': 'T20I # 1842'},
   {'team1': 'Bangladesh',
    'team2': 'Netherlands',
    'winner': 'Bangladesh',
    'margin': '9 runs',
    'ground': 'Hobart',
    'matchDate': 'Oct 24, 2022',
    'scorecard': 'T20I # 1843'},
   {'team1': 'South Africa',
    'team2': 'Zimbabwe',
    'winner': 'no result',
    'margin': '',
    'ground': 'Hobart',
    'matchDate': 'Oct 24, 2022',
    'scorecard': 'T20I # 1844'},
   {'team1': 'Australia',
    'team2': 'Sri Lanka',
    'winner': 'Australia',
    'margin': '7 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 25, 2022',
    'scorecard': 'T20I # 1845'},
   {'team1': 'England',
    'team2': 'Ireland',
    'winner': 'Ireland',
    'margin': '5 runs',
    'ground': 'Melbourne',
    'matchDate': 'Oct 26, 2022',
    'scorecard': 'T20I # 1846'},
   {'team1': 'Afghanistan',
    'team2': 'New Zealand',
    'winner': 'abandoned',
    'margin': '',
    'ground': 'Melbourne',
    'matchDate': 'Oct 26, 2022',
    'scorecard': 'T20I # 1846a'},
   {'team1': 'Bangladesh',
    'team2': 'South Africa',
    'winner': 'South Africa',
    'margin': '104 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 27, 2022',
    'scorecard': 'T20I # 1847'},
   {'team1': 'India',
    'team2': 'Netherlands',
    'winner': 'India',
    'margin': '56 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 27, 2022',
    'scorecard': 'T20I # 1848'},
   {'team1': 'Pakistan',
    'team2': 'Zimbabwe',
    'winner': 'Zimbabwe',
    'margin': '1 run',
    'ground': 'Perth',
    'matchDate': 'Oct 27, 2022',
    'scorecard': 'T20I # 1849'},
   {'team1': 'Afghanistan',
    'team2': 'Ireland',
    'winner': 'abandoned',
    'margin': '',
    'ground': 'Melbourne',
    'matchDate': 'Oct 28, 2022',
    'scorecard': 'T20I # 1849a'},
   {'team1': 'Australia',
    'team2': 'England',
    'winner': 'abandoned',
    'margin': '',
    'ground': 'Melbourne',
    'matchDate': 'Oct 28, 2022',
    'scorecard': 'T20I # 1849b'},
   {'team1': 'New Zealand',
    'team2': 'Sri Lanka',
    'winner': 'New Zealand',
    'margin': '65 runs',
    'ground': 'Sydney',
    'matchDate': 'Oct 29, 2022',
    'scorecard': 'T20I # 1850'},
   {'team1': 'Bangladesh',
    'team2': 'Zimbabwe',
    'winner': 'Bangladesh',
    'margin': '3 runs',
    'ground': 'Brisbane',
    'matchDate': 'Oct 30, 2022',
    'scorecard': 'T20I # 1851'},
   {'team1': 'Netherlands',
    'team2': 'Pakistan',
    'winner': 'Pakistan',
    'margin': '6 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 30, 2022',
    'scorecard': 'T20I # 1852'},
   {'team1': 'India',
    'team2': 'South Africa',
    'winner': 'South Africa',
    'margin': '5 wickets',
    'ground': 'Perth',
    'matchDate': 'Oct 30, 2022',
    'scorecard': 'T20I # 1853'},
   {'team1': 'Australia',
    'team2': 'Ireland',
    'winner': 'Australia',
    'margin': '42 runs',
    'ground': 'Brisbane',
    'matchDate': 'Oct 31, 2022',
    'scorecard': 'T20I # 1855'},
   {'team1': 'Afghanistan',
    'team2': 'Sri Lanka',
    'winner': 'Sri Lanka',
    'margin': '6 wickets',
    'ground': 'Brisbane',
    'matchDate': 'Nov 1, 2022',
    'scorecard': 'T20I # 1856'},
   {'team1': 'England',
    'team2': 'New Zealand',
    'winner': 'England',
    'margin': '20 runs',
    'ground': 'Brisbane',
    'matchDate': 'Nov 1, 2022',
    'scorecard': 'T20I # 1858'},
   {'team1': 'Netherlands',
    'team2': 'Zimbabwe',
    'winner': 'Netherlands',
    'margin': '5 wickets',
    'ground': 'Adelaide',
    'matchDate': 'Nov 2, 2022',
    'scorecard': 'T20I # 1859'},
   {'team1': 'Bangladesh',
    'team2': 'India',
    'winner': 'India',
    'margin': '5 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 2, 2022',
    'scorecard': 'T20I # 1860'},
   {'team1': 'Pakistan',
    'team2': 'South Africa',
    'winner': 'Pakistan',
    'margin': '33 runs',
    'ground': 'Sydney',
    'matchDate': 'Nov 3, 2022',
    'scorecard': 'T20I # 1861'},
   {'team1': 'Ireland',
    'team2': 'New Zealand',
    'winner': 'New Zealand',
    'margin': '35 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 4, 2022',
    'scorecard': 'T20I # 1862'},
   {'team1': 'Australia',
    'team2': 'Afghanistan',
    'winner': 'Australia',
    'margin': '4 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 4, 2022',
    'scorecard': 'T20I # 1864'},
   {'team1': 'England',
    'team2': 'Sri Lanka',
    'winner': 'England',
    'margin': '4 wickets',
    'ground': 'Sydney',
    'matchDate': 'Nov 5, 2022',
    'scorecard': 'T20I # 1867'},
   {'team1': 'Netherlands',
    'team2': 'South Africa',
    'winner': 'Netherlands',
    'margin': '13 runs',
    'ground': 'Adelaide',
    'matchDate': 'Nov 6, 2022',
    'scorecard': 'T20I # 1871'},
   {'team1': 'Bangladesh',
    'team2': 'Pakistan',
    'winner': 'Pakistan',
    'margin': '5 wickets',
    'ground': 'Adelaide',
    'matchDate': 'Nov 6, 2022',
    'scorecard': 'T20I # 1872'},
   {'team1': 'India',
    'team2': 'Zimbabwe',
    'winner': 'India',
    'margin': '71 runs',
    'ground': 'Melbourne',
    'matchDate': 'Nov 6, 2022',
    'scorecard': 'T20I # 1873'},
   {'team1': 'New Zealand',
    'team2': 'Pakistan',
    'winner': 'Pakistan',
    'margin': '7 wickets',
    'ground': 'Sydney',
    'matchDate': 'Nov 9, 2022',
    'scorecard': 'T20I # 1877'},
   {'team1': 'England',
    'team2': 'India',
    'winner': 'England',
    'margin': '10 wickets',
    'ground': 'Adelaide',
    'matchDate': 'Nov 10, 2022',
    'scorecard': 'T20I # 1878'},
   {'team1': 'England',
    'team2': 'Pakistan',
    'winner': 'England',
    'margin': '5 wickets',
    'ground': 'Melbourne',
    'matchDate': 'Nov 13, 2022',
    'scorecard': 'T20I # 1879'}]}]

In [5]:
data[0]["matchSummary"]

[{'team1': 'Namibia',
  'team2': 'Sri Lanka',
  'winner': 'Namibia',
  'margin': '55 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 16, 2022',
  'scorecard': 'T20I # 1823'},
 {'team1': 'Netherlands',
  'team2': 'U.A.E.',
  'winner': 'Netherlands',
  'margin': '3 wickets',
  'ground': 'Geelong',
  'matchDate': 'Oct 16, 2022',
  'scorecard': 'T20I # 1825'},
 {'team1': 'Scotland',
  'team2': 'West Indies',
  'winner': 'Scotland',
  'margin': '42 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 17, 2022',
  'scorecard': 'T20I # 1826'},
 {'team1': 'Ireland',
  'team2': 'Zimbabwe',
  'winner': 'Zimbabwe',
  'margin': '31 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 17, 2022',
  'scorecard': 'T20I # 1828'},
 {'team1': 'Namibia',
  'team2': 'Netherlands',
  'winner': 'Netherlands',
  'margin': '5 wickets',
  'ground': 'Geelong',
  'matchDate': 'Oct 18, 2022',
  'scorecard': 'T20I # 1830'},
 {'team1': 'Sri Lanka',
  'team2': 'U.A.E.',
  'winner': 'Sri Lanka',
  'margin': '79 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 18, 2022',
  'scorecard': 'T20I # 1832'},
 {'team1': 'Ireland',
  'team2': 'Scotland',
  'winner': 'Ireland',
  'margin': '6 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 19, 2022',
  'scorecard': 'T20I # 1833'},
 {'team1': 'West Indies',
  'team2': 'Zimbabwe',
  'winner': 'West Indies',
  'margin': '31 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 19, 2022',
  'scorecard': 'T20I # 1834'},
 {'team1': 'Netherlands',
  'team2': 'Sri Lanka',
  'winner': 'Sri Lanka',
  'margin': '16 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 20, 2022',
  'scorecard': 'T20I # 1835'},
 {'team1': 'Namibia',
  'team2': 'U.A.E.',
  'winner': 'U.A.E.',
  'margin': '7 runs',
  'ground': 'Geelong',
  'matchDate': 'Oct 20, 2022',
  'scorecard': 'T20I # 1836'},
 {'team1': 'Ireland',
  'team2': 'West Indies',
  'winner': 'Ireland',
  'margin': '9 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 21, 2022',
  'scorecard': 'T20I # 1837'},
 {'team1': 'Scotland',
  'team2': 'Zimbabwe',
  'winner': 'Zimbabwe',
  'margin': '5 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 21, 2022',
  'scorecard': 'T20I # 1838'},
 {'team1': 'Australia',
  'team2': 'New Zealand',
  'winner': 'New Zealand',
  'margin': '89 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 22, 2022',
  'scorecard': 'T20I # 1839'},
 {'team1': 'Afghanistan',
  'team2': 'England',
  'winner': 'England',
  'margin': '5 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 22, 2022',
  'scorecard': 'T20I # 1840'},
 {'team1': 'Ireland',
  'team2': 'Sri Lanka',
  'winner': 'Sri Lanka',
  'margin': '9 wickets',
  'ground': 'Hobart',
  'matchDate': 'Oct 23, 2022',
  'scorecard': 'T20I # 1841'},
 {'team1': 'India',
  'team2': 'Pakistan',
  'winner': 'India',
  'margin': '4 wickets',
  'ground': 'Melbourne',
  'matchDate': 'Oct 23, 2022',
  'scorecard': 'T20I # 1842'},
 {'team1': 'Bangladesh',
  'team2': 'Netherlands',
  'winner': 'Bangladesh',
  'margin': '9 runs',
  'ground': 'Hobart',
  'matchDate': 'Oct 24, 2022',
  'scorecard': 'T20I # 1843'},
 {'team1': 'South Africa',
  'team2': 'Zimbabwe',
  'winner': 'no result',
  'margin': '',
  'ground': 'Hobart',
  'matchDate': 'Oct 24, 2022',
  'scorecard': 'T20I # 1844'},
 {'team1': 'Australia',
  'team2': 'Sri Lanka',
  'winner': 'Australia',
  'margin': '7 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 25, 2022',
  'scorecard': 'T20I # 1845'},
 {'team1': 'England',
  'team2': 'Ireland',
  'winner': 'Ireland',
  'margin': '5 runs',
  'ground': 'Melbourne',
  'matchDate': 'Oct 26, 2022',
  'scorecard': 'T20I # 1846'},
 {'team1': 'Afghanistan',
  'team2': 'New Zealand',
  'winner': 'abandoned',
  'margin': '',
  'ground': 'Melbourne',
  'matchDate': 'Oct 26, 2022',
  'scorecard': 'T20I # 1846a'},
 {'team1': 'Bangladesh',
  'team2': 'South Africa',
  'winner': 'South Africa',
  'margin': '104 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 27, 2022',
  'scorecard': 'T20I # 1847'},
 {'team1': 'India',
  'team2': 'Netherlands',
  'winner': 'India',
  'margin': '56 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 27, 2022',
  'scorecard': 'T20I # 1848'},
 {'team1': 'Pakistan',
  'team2': 'Zimbabwe',
  'winner': 'Zimbabwe',
  'margin': '1 run',
  'ground': 'Perth',
  'matchDate': 'Oct 27, 2022',
  'scorecard': 'T20I # 1849'},
 {'team1': 'Afghanistan',
  'team2': 'Ireland',
  'winner': 'abandoned',
  'margin': '',
  'ground': 'Melbourne',
  'matchDate': 'Oct 28, 2022',
  'scorecard': 'T20I # 1849a'},
 {'team1': 'Australia',
  'team2': 'England',
  'winner': 'abandoned',
  'margin': '',
  'ground': 'Melbourne',
  'matchDate': 'Oct 28, 2022',
  'scorecard': 'T20I # 1849b'},
 {'team1': 'New Zealand',
  'team2': 'Sri Lanka',
  'winner': 'New Zealand',
  'margin': '65 runs',
  'ground': 'Sydney',
  'matchDate': 'Oct 29, 2022',
  'scorecard': 'T20I # 1850'},
 {'team1': 'Bangladesh',
  'team2': 'Zimbabwe',
  'winner': 'Bangladesh',
  'margin': '3 runs',
  'ground': 'Brisbane',
  'matchDate': 'Oct 30, 2022',
  'scorecard': 'T20I # 1851'},
 {'team1': 'Netherlands',
  'team2': 'Pakistan',
  'winner': 'Pakistan',
  'margin': '6 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 30, 2022',
  'scorecard': 'T20I # 1852'},
 {'team1': 'India',
  'team2': 'South Africa',
  'winner': 'South Africa',
  'margin': '5 wickets',
  'ground': 'Perth',
  'matchDate': 'Oct 30, 2022',
  'scorecard': 'T20I # 1853'},
 {'team1': 'Australia',
  'team2': 'Ireland',
  'winner': 'Australia',
  'margin': '42 runs',
  'ground': 'Brisbane',
  'matchDate': 'Oct 31, 2022',
  'scorecard': 'T20I # 1855'},
 {'team1': 'Afghanistan',
  'team2': 'Sri Lanka',
  'winner': 'Sri Lanka',
  'margin': '6 wickets',
  'ground': 'Brisbane',
  'matchDate': 'Nov 1, 2022',
  'scorecard': 'T20I # 1856'},
 {'team1': 'England',
  'team2': 'New Zealand',
  'winner': 'England',
  'margin': '20 runs',
  'ground': 'Brisbane',
  'matchDate': 'Nov 1, 2022',
  'scorecard': 'T20I # 1858'},
 {'team1': 'Netherlands',
  'team2': 'Zimbabwe',
  'winner': 'Netherlands',
  'margin': '5 wickets',
  'ground': 'Adelaide',
  'matchDate': 'Nov 2, 2022',
  'scorecard': 'T20I # 1859'},
 {'team1': 'Bangladesh',
  'team2': 'India',
  'winner': 'India',
  'margin': '5 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 2, 2022',
  'scorecard': 'T20I # 1860'},
 {'team1': 'Pakistan',
  'team2': 'South Africa',
  'winner': 'Pakistan',
  'margin': '33 runs',
  'ground': 'Sydney',
  'matchDate': 'Nov 3, 2022',
  'scorecard': 'T20I # 1861'},
 {'team1': 'Ireland',
  'team2': 'New Zealand',
  'winner': 'New Zealand',
  'margin': '35 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 4, 2022',
  'scorecard': 'T20I # 1862'},
 {'team1': 'Australia',
  'team2': 'Afghanistan',
  'winner': 'Australia',
  'margin': '4 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 4, 2022',
  'scorecard': 'T20I # 1864'},
 {'team1': 'England',
  'team2': 'Sri Lanka',
  'winner': 'England',
  'margin': '4 wickets',
  'ground': 'Sydney',
  'matchDate': 'Nov 5, 2022',
  'scorecard': 'T20I # 1867'},
 {'team1': 'Netherlands',
  'team2': 'South Africa',
  'winner': 'Netherlands',
  'margin': '13 runs',
  'ground': 'Adelaide',
  'matchDate': 'Nov 6, 2022',
  'scorecard': 'T20I # 1871'},
 {'team1': 'Bangladesh',
  'team2': 'Pakistan',
  'winner': 'Pakistan',
  'margin': '5 wickets',
  'ground': 'Adelaide',
  'matchDate': 'Nov 6, 2022',
  'scorecard': 'T20I # 1872'},
 {'team1': 'India',
  'team2': 'Zimbabwe',
  'winner': 'India',
  'margin': '71 runs',
  'ground': 'Melbourne',
  'matchDate': 'Nov 6, 2022',
  'scorecard': 'T20I # 1873'},
 {'team1': 'New Zealand',
  'team2': 'Pakistan',
  'winner': 'Pakistan',
  'margin': '7 wickets',
  'ground': 'Sydney',
  'matchDate': 'Nov 9, 2022',
  'scorecard': 'T20I # 1877'},
 {'team1': 'England',
  'team2': 'India',
  'winner': 'England',
  'margin': '10 wickets',
  'ground': 'Adelaide',
  'matchDate': 'Nov 10, 2022',
  'scorecard': 'T20I # 1878'},
 {'team1': 'England',
  'team2': 'Pakistan',
  'winner': 'England',
  'margin': '5 wickets',
  'ground': 'Melbourne',
  'matchDate': 'Nov 13, 2022',
  'scorecard': 'T20I # 1879'}]

In [13]:
df_match = pd.DataFrame(data[0]['matchSummary'])
df_match.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [17]:
# make scorecard as primary key so that we can link to many tables
df_match.rename({'scorecard':'match_id'},axis = 1, inplace = True)
df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [18]:
df_match.shape

(45, 7)

In [19]:
match_ids_dict = {}
for index,row in df_match.iterrows():
    key1 =  row["team1"]+" Vs "+row["team2"]
    key2 = row["team2"]+" Vs " + row["team1"]
    match_ids_dict[key1] = row["match_id"]
    match_ids_dict[key2] = row["match_id"]
match_ids_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 'U.A.E. Vs Netherlands': 'T20I # 1825',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Sri Lanka Vs U.A.E.': 'T20I # 1832',
 'U.A.E. Vs Sri Lanka': 'T20I # 1832',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Namibia Vs U.A.E.': 'T20I # 1836',
 'U.A.E. Vs Namibia': 'T20I # 1836',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Afghanistan Vs New Zealand': 'T20I # 1846a',
 'New Zealand Vs Afghanistan': 'T20I # 1846a',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'Afghanistan Vs Ireland': 'T20I # 1849a',
 'Ireland Vs Afghanistan': 'T20I # 1849a',
 'Australia Vs England': 'T20I # 1849b',
 'England Vs Australia': 'T20I # 1849b',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879'}

**batting_summary**

In [22]:
with open("C:\\Users\\Bhavya Sree\\Downloads\\t20_wc_batting_summary.json") as f:
    data = json.load(f)
    all_records = []
    for rec in data:
        all_records.extend(rec["battingSummary"])
df_batting = pd.DataFrame(all_records)
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00

In [11]:
df_batting.shape

(699, 10)

In [23]:
df_batting["out/notout"] = df_batting.dismissal.apply(lambda x: "out" if len(x) > 0 else "notout")
df_batting

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/notout
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
...,...,...,...,...,...,...,...,...,...,...,...
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11,out
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12,notout
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95,out
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15,out
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00,notout

In [24]:
df_batting.drop(columns=['dismissal'],inplace = True)
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/notout
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,notout
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out

In [25]:
df_batting["batsmanName"] = df_batting["batsmanName"].apply(lambda x:x.replace("â€",""))
df_batting["batsmanName"] = df_batting["batsmanName"].apply(lambda x:x.replace("\xa0",""))
df_batting

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/notout
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
...,...,...,...,...,...,...,...,...,...,...
694,Pakistan Vs England,England,3,Phil Salt,10,9,2,0,111.11,out
695,Pakistan Vs England,England,4,Ben Stokes,52,49,5,1,106.12,notout
696,Pakistan Vs England,England,5,Harry Brook,20,23,1,0,86.95,out
697,Pakistan Vs England,England,6,Moeen Ali,19,13,3,0,146.15,out
698,Pakistan Vs England,England,7,Liam Livingstone,1,1,0,0,100.00,notout

In [26]:
df_batting.head(40)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/notout
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,notout
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,notout
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,out
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),1,2,0,0,50.00,out
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,notout
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,notout
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out
30,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,23,18,3,1,127.77,out
31,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,14,18,1,0,77.77,out
32,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,17,19,1,0,89.47,out
33,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,8,16,0,0,50.00,out
34,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards(c),16,19,0,0,84.21,notout
35,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,0,2,0,0,0.00,out
36,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,15,16,0,0,93.75,out
37,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,4,4,0,0,100.00,notout
38,Scotland Vs West Indies,Scotland,1,George Munsey,66,53,9,0,124.52,notout
39,Scotland Vs West Indies,Scotland,2,Michael Jones,20,17,3,0,117.64,out

In [27]:
df_batting["match_id"] = df_batting["match"].map(match_ids_dict)
df_batting.head(40)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/notout,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out,T20I # 1823
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out,T20I # 1823
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out,T20I # 1823
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,notout,T20I # 1823
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out,T20I # 1823
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out,T20I # 1823
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out,T20I # 1823
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out,T20I # 1823
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out,T20I # 1823
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out,T20I # 1823
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out,T20I # 1823
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out,T20I # 1823
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out,T20I # 1823
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out,T20I # 1823
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,notout,T20I # 1823
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out,T20I # 1825
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out,T20I # 1825
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out,T20I # 1825
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,out,T20I # 1825
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out,T20I # 1825
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out,T20I # 1825
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),1,2,0,0,50.00,out,T20I # 1825
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out,T20I # 1825
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,notout,T20I # 1825
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,notout,T20I # 1825
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out,T20I # 1825
30,U.A.E. Vs Netherlands,Netherlands,2,Max O'Dowd,23,18,3,1,127.77,out,T20I # 1825
31,U.A.E. Vs Netherlands,Netherlands,3,Bas de Leede,14,18,1,0,77.77,out,T20I # 1825
32,U.A.E. Vs Netherlands,Netherlands,4,Colin Ackermann,17,19,1,0,89.47,out,T20I # 1825
33,U.A.E. Vs Netherlands,Netherlands,5,Tom Cooper,8,16,0,0,50.00,out,T20I # 1825
34,U.A.E. Vs Netherlands,Netherlands,6,Scott Edwards(c),16,19,0,0,84.21,notout,T20I # 1825
35,U.A.E. Vs Netherlands,Netherlands,7,Roelof van der Merwe,0,2,0,0,0.00,out,T20I # 1825
36,U.A.E. Vs Netherlands,Netherlands,8,Tim Pringle,15,16,0,0,93.75,out,T20I # 1825
37,U.A.E. Vs Netherlands,Netherlands,9,Logan van Beek,4,4,0,0,100.00,notout,T20I # 1825
38,Scotland Vs West Indies,Scotland,1,George Munsey,66,53,9,0,124.52,notout,T20I # 1826
39,Scotland Vs West Indies,Scotland,2,Michael Jones,20,17,3,0,117.64,out,T20I # 1826

In [28]:
df_batting[df_batting["teamInnings"]=="India"]

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/notout,match_id
259,Pakistan Vs India,India,1,KL Rahul,4,8,0,0,50.00,out,T20I # 1842
260,Pakistan Vs India,India,2,Rohit Sharma(c),4,7,0,0,57.14,out,T20I # 1842
261,Pakistan Vs India,India,3,Virat Kohli,82,53,6,4,154.71,notout,T20I # 1842
262,Pakistan Vs India,India,4,Suryakumar Yadav,15,10,2,0,150.00,out,T20I # 1842
263,Pakistan Vs India,India,5,Axar Patel,2,3,0,0,66.66,out,T20I # 1842
264,Pakistan Vs India,India,6,Hardik Pandya,40,37,1,2,108.10,out,T20I # 1842
265,Pakistan Vs India,India,7,Dinesh Karthik,1,2,0,0,50.00,out,T20I # 1842
266,Pakistan Vs India,India,8,Ravichandran Ashwin,1,1,0,0,100.00,notout,T20I # 1842
345,India Vs Netherlands,India,1,KL Rahul,9,12,1,0,75.00,out,T20I # 1848
346,India Vs Netherlands,India,2,Rohit Sharma(c),53,39,4,3,135.89,out,T20I # 1848
347,India Vs Netherlands,India,3,Virat Kohli,62,44,3,2,140.90,notout,T20I # 1848
348,India Vs Netherlands,India,4,Suryakumar Yadav,51,25,7,1,204.00,notout,T20I # 1848
434,India Vs South Africa,India,1,KL Rahul,9,14,0,1,64.28,out,T20I # 1853
435,India Vs South Africa,India,2,Rohit Sharma(c),15,14,1,1,107.14,out,T20I # 1853
436,India Vs South Africa,India,3,Virat Kohli,12,11,2,0,109.09,out,T20I # 1853
437,India Vs South Africa,India,4,Suryakumar Yadav,68,40,6,3,170.00,out,T20I # 1853
438,India Vs South Africa,India,5,Deepak Hooda,0,3,0,0,0.00,out,T20I # 1853
439,India Vs South Africa,India,6,Hardik Pandya,2,3,0,0,66.66,out,T20I # 1853
440,India Vs South Africa,India,7,Dinesh Karthik,6,15,0,0,40.00,out,T20I # 1853
441,India Vs South Africa,India,8,Ravichandran Ashwin,7,11,0,0,63.63,out,T20I # 1853
442,India Vs South Africa,India,9,Bhuvneshwar Kumar,4,6,0,0,66.66,notout,T20I # 1853
443,India Vs South Africa,India,10,Mohammed Shami,0,2,0,0,0.00,out,T20I # 1853
444,India Vs South Africa,India,11,Arshdeep Singh,2,1,0,0,200.00,notout,T20I # 1853
519,India Vs Bangladesh,India,1,KL Rahul,50,32,3,4,156.25,out,T20I # 1860
520,India Vs Bangladesh,India,2,Rohit Sharma(c),2,8,0,0,25.00,out,T20I # 1860
521,India Vs Bangladesh,India,3,Virat Kohli,64,44,8,1,145.45,notout,T20I # 1860
522,India Vs Bangladesh,India,4,Suryakumar Yadav,30,16,4,0,187.50,out,T20I # 1860
523,India Vs Bangladesh,India,5,Hardik Pandya,5,6,0,0,83.33,out,T20I # 1860
524,India Vs Bangladesh,India,6,Dinesh Karthik,7,5,1,0,140.00,out,T20I # 1860
525,India Vs Bangladesh,India,7,Axar Patel,7,6,1,0,116.66,out,T20I # 1860
526,India Vs Bangladesh,India,8,Ravichandran Ashwin,13,6,1,1,216.66,notout,T20I # 1860
644,India Vs Zimbabwe,India,1,KL Rahul,51,35,3,3,145.71,out,T20I # 1873
645,India Vs Zimbabwe,India,2,Rohit Sharma(c),15,13,2,0,115.38,out,T20I # 1873
646,India Vs Zimbabwe,India,3,Virat Kohli,26,25,2,0,104.00,out,T20I # 1873
647,India Vs Zimbabwe,India,4,Suryakumar Yadav,61,25,6,4,244.00,notout,T20I # 1873
648,India Vs Zimbabwe,India,5,Rishabh Pant,3,5,0,0,60.00,out,T20I # 1873
649,India Vs Zimbabwe,India,6,Hardik Pandya,18,18,2,0,100.00,out,T20I # 1873
650,India Vs Zimbabwe,India,7,Axar Patel,0,0,0,0,-,notout,T20I # 1873
673,India Vs England,India,1,KL Rahul,5,5,1,0,100.00,out,T20I # 1878
674,India Vs England,India,2,Rohit Sharma(c),27,28,4,0,96.42,out,T20I # 1878
675,India Vs England,India,3,Virat Kohli,50,40,4,1,125.00,out,T20I # 1878
676,India Vs England,India,4,Suryakumar Yadav,14,10,1,1,140.00,out,T20I # 1878
677,India Vs England,India,5,Hardik Pandya,63,33,4,5,190.90,out,T20I # 1878
678,India Vs England,India,6,Rishabh Pant,6,4,1,0,150.00,out,T20I # 1878
679,India Vs England,India,7,Ravichandran Ashwin,0,0,0,0,-,notout,T20I # 1878

In [18]:
import os

directory = 't20_csv_files'
if not os.path.exists(directory):
    os.makedirs(directory)

df_batting.to_csv(os.path.join(directory, 'temp.csv'))

In [19]:
df_batting.to_csv(r"C:\Users\Public\Downloads\temporary_me.csv",index=False)

In [30]:
with open('C:\\Users\\Bhavya Sree\\Downloads\\t20_wc_bowling_summary.json') as f:
    data = json.load(f)
    all_records = []
    for rec in data:
        all_records.extend(rec['bowlingSummary'])
all_records[:2]

[{'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Maheesh Theekshana',
  'overs': '4',
  'maiden': '0',
  'runs': '23',
  'wickets': '1',
  'economy': '5.75',
  '0s': '7',
  '4s': '0',
  '6s': '0',
  'wides': '2',
  'noBalls': '0'},
 {'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Dushmantha Chameera',
  'overs': '4',
  'maiden': '0',
  'runs': '39',
  'wickets': '1',
  'economy': '9.75',
  '0s': '6',
  '4s': '3',
  '6s': '1',
  'wides': '2',
  'noBalls': '0'}]

In [31]:
df_bowling = pd.DataFrame(all_records)
print(df_bowling.shape)
df_bowling.head()

(500, 13)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0

In [32]:
df_bowling['match_id'] = df_bowling['match'].map(match_ids_dict)
df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823

In [34]:
df_bowling.to_csv('t20_csv_files/fact_bowling_summary.csv', index = False)

# process player information

In [36]:
with open('C:\\Users\\Bhavya Sree\\Downloads\\t20_wc_player_info.json') as f:
    data = json.load(f)

In [37]:
df_players = pd.DataFrame(data)

print(df_players.shape)
df_players.head(10)

(219, 6)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendisâ€,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."

In [38]:
df_players['name'] = df_players['name'].apply(lambda x: x.replace('â€', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('†', ''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('\xa0', ''))
df_players.head(10)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."

In [39]:
df_players[df_players['team'] == 'India']

,name,team,battingStyle,bowlingStyle,playingRole,description
127,KL Rahul,India,Right hand Bat,,Opening Batter,"A tall, elegant right-hand batsman who can kee..."
128,Rohit Sharma(c),India,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
129,Virat Kohli,India,Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
130,Suryakumar Yadav,India,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
131,Axar Patel,India,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
132,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Hardik Pandya swears by living life king size ...
133,Dinesh Karthik,India,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
134,Ravichandran Ashwin,India,Right hand Bat,Right arm Offbreak,Bowling Allrounder,R Ashwin took the tricks and skills he learned...
135,Bhuvneshwar Kumar,India,Right hand Bat,Right arm Medium,Bowler,"At the time of his India debut in 2012, Bhuvne..."
136,Arshdeep Singh,India,Left hand Bat,Left arm Medium fast,Bowler,
137,Mohammed Shami,India,Right hand Bat,Right arm Fast,Bowler,Mohammed Shami was India's leading fast bowler...
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
211,Rishabh Pant,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."

In [40]:
df_players.to_csv('t20_csv_files/dim_players_no_images.csv', index = False)